default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # list of supported hooks: https://pre-commit.com/hooks.html
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-case-conflict
      - id: check-added-large-files

  # Ruff formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.2
    hooks:
      - id: ruff # This is the linter
        args:
          - --fix
          - --ignore=F401 # Ignore unused imports
          - --ignore=F841 # Ignore unused variables
      - id: ruff-format # This is the formatter
        args:
          - --line-length=99

  # Jupyter notebook cell output clearing
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout

  # Markdown linter
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.43.0
    hooks:
      - id: markdownlint
        args:
          - --disable=MD013 # Line length limitation
          # - --disable=MD029 # Line numbering in ordered list
          - --disable=MD033 # No inline html
          # - --disable=MD047
